### ISSUE TITLE
Wrong unprocessed keywords: ["type"] error when using propertyNames with $ref

### ISSUE THREAD

**Issue by zepatrik** [ExodusMovement/schemasafe#138]
In my example (https://github.com/zepatrik/schemasafe-propertyNames-example) schemasafe reports an unprocessed keyword error. The problem is there is no `"type"` keyword at the position it is reported. I tried several different things to circumvent this error but nothing worked.
The problem seems to be rooted at using `"$ref"` with `"propertyNames"`, as moving the definition into the `"propertyNames"` schema works.
See also https://github.com/SchemaStore/schemastore/pull/1312 where this initially came up.

**Comment by ChALkeR** [comment]
@zepatrik Thanks for the testcase! Investigating.

**Comment by ChALkeR** [comment]
Fixed in aa8fd5797dba4297519746d483456647a25652cb.
Thanks again!

**Comment by ffjanhoeck** [comment]
When this will be released @ChALkeR ? :) I need that bugfix as well :)

**Comment by GerryFerdinandus** [comment]
This issue is fix and closed. But for the user of this product the issue is still not fixed because it is not yet released!
